// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlite

import (
	"database/sql"
	"time"
)

type Comic struct {
	ID          int64
	Titles      string
	Author      sql.NullString
	Description sql.NullString
	Cover       sql.NullString
	PublishedIn string
	Genres      string
	ComType     int64
	Status      int64
	Rating      int64
	CurrentChap int64
	ViewedChap  int64
	Track       bool
	Deleted     bool
	LastUpdate  time.Time
}
