// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: comics.proto

package pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Comics with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Comics) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Comics with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ComicsMultiError, or nil if none found.
func (m *Comics) ValidateAll() error {
	return m.validate(true)
}

func (m *Comics) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetComics() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ComicsValidationError{
						field:  fmt.Sprintf("Comics[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ComicsValidationError{
						field:  fmt.Sprintf("Comics[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ComicsValidationError{
					field:  fmt.Sprintf("Comics[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ComicsMultiError(errors)
	}

	return nil
}

// ComicsMultiError is an error wrapping multiple validation errors returned by
// Comics.ValidateAll() if the designated constraints aren't met.
type ComicsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ComicsMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ComicsMultiError) AllErrors() []error { return m }

// ComicsValidationError is the validation error returned by Comics.Validate if
// the designated constraints aren't met.
type ComicsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ComicsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ComicsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ComicsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ComicsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ComicsValidationError) ErrorName() string { return "ComicsValidationError" }

// Error satisfies the builtin error interface
func (e ComicsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sComics.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ComicsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ComicsValidationError{}

// Validate checks the field values on Comic with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Comic) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Comic with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ComicMultiError, or nil if none found.
func (m *Comic) ValidateAll() error {
	return m.validate(true)
}

func (m *Comic) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		err := ComicValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(m.GetTitles()) < 1 {
		err := ComicValidationError{
			field:  "Titles",
			reason: "value must contain at least 1 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetTitles() {
		_, _ = idx, item

		if utf8.RuneCountInString(item) < 1 {
			err := ComicValidationError{
				field:  fmt.Sprintf("Titles[%v]", idx),
				reason: "value length must be at least 1 runes",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	// no validation rules for Author

	// no validation rules for Description

	// no validation rules for Type

	// no validation rules for Status

	if uri, err := url.Parse(m.GetCover()); err != nil {
		err = ComicValidationError{
			field:  "Cover",
			reason: "value must be a valid URI",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	} else if !uri.IsAbs() {
		err := ComicValidationError{
			field:  "Cover",
			reason: "value must be absolute",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetCurrentChap() < 0 {
		err := ComicValidationError{
			field:  "CurrentChap",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetLastUpdate()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ComicValidationError{
					field:  "LastUpdate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ComicValidationError{
					field:  "LastUpdate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetLastUpdate()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ComicValidationError{
				field:  "LastUpdate",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Track

	if m.GetViewedChap() < 0 {
		err := ComicValidationError{
			field:  "ViewedChap",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Deleted

	if len(errors) > 0 {
		return ComicMultiError(errors)
	}

	return nil
}

// ComicMultiError is an error wrapping multiple validation errors returned by
// Comic.ValidateAll() if the designated constraints aren't met.
type ComicMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ComicMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ComicMultiError) AllErrors() []error { return m }

// ComicValidationError is the validation error returned by Comic.Validate if
// the designated constraints aren't met.
type ComicValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ComicValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ComicValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ComicValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ComicValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ComicValidationError) ErrorName() string { return "ComicValidationError" }

// Error satisfies the builtin error interface
func (e ComicValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sComic.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ComicValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ComicValidationError{}
