version: '3'
services:
  postgres:
    container_name: comic-postgres
    image: 'postgres:12.10'
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
      PGDATA: /var/lib/postgresql/data/pgdata
      # Delete previous volumes to apply changes here
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5

  jaeger:
    container_name: comic-jaeger
    image: jaegertracing/all-in-one:1.47
    restart: always
    ports:
      - "6831:6831/udp"   # Jaeger agent - accepts spans in Thrift format
      - "6832:6832/udp"   # Jaeger agent - accepts spans in Thrift format
      - "5775:5775/udp"   # Jaeger agent - accepts spans in Thrift format (legacy)
      - "14250:14250"     # Jaeger collector - accepts spans in model.proto format
      - "14268:14268"     # Jaeger collector - accepts spans in Thrift format
      - "16686:16686"     # Jaeger UI
      - "4317:4317"       # OTLP gRPC
      - "4318:4318"       # OTLP HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    healthcheck:
      test: ["CMD", "wget", "--spider", "localhost:16686"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  pgdata:
    driver: local