---
apiVersion: 1
datasources:
  - name: jaeger_comics
    type: jaeger
    access: proxy
    orgId: 1
    url: http://jaeger:16686
  - name: prom_comics
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
  - name: loki_comics
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100