{
 "title": "Go build",
 "description": "A basic visualization of the main metrics of the comic service app",
 "tags": [ "comics" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Query Duration ",
   "type": "timeseries",
   "description": "Histogram of query durations",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, instance) (rate(comics_service_user_repo_query_duration_seconds_bucket[5m])))",
     "legendFormat": "p95 {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, instance) (rate(comics_service_user_repo_query_duration_seconds_bucket[5m])))",
     "legendFormat": "p99 {{instance}}"
    },
    {
     "expr": "sum by(instance) (comics_service_user_repo_query_duration_seconds_sum) / sum  by(instance) (comics_service_user_repo_query_duration_seconds_count)",
     "legendFormat": "Avg {{instance}}"
    }
   ]
  },
  {
   "title": "Error rate on DB queries",
   "type": "gauge",
   "description": "Errors include 404 responses from the DB, and any other possible error.",
   "gridPos": { "h": 9, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "comics_service_user_repo_error_rate",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "# of DB queries",
   "type": "timeseries",
   "description": "Number of database queries per operation",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(operation) (comics_service_user_repo_queries_total)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "# of requests per URI",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(uri, instance, code) (gin_uri_request_total{method!=\"OPTIONS\", uri!=\"/swagger/*any\"})",
     "legendFormat": "{{instance}}{{uri}}  - {{code}}"
    }
   ]
  },
  {
   "title": "Users Views",
   "type": "timeseries",
   "description": "Users Views, all the received IP numbers on the server.",
   "gridPos": { "h": 9, "w": 4, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "gin_request_uv_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Go build version",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_build_info{version!=\"(devel)\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Code",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(code, instance) (gin_uri_request_total)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Traffic In-Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(gin_request_body_total[5m])",
     "legendFormat": "{{instance}}-in"
    },
    {
     "expr": "rate(gin_response_body_total[5m])",
     "legendFormat": "{{instance}}-out"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum (rate(gin_request_duration_bucket[5m])) by (le, instance))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum (rate(gin_request_duration_bucket[5m])) by (le, instance))",
     "legendFormat": "p99"
    },
    {
     "expr": "sum by(instance) (gin_request_duration_sum) / sum by(instance) (gin_request_duration_count)",
     "legendFormat": "avg"
    }
   ]
  }
 ]
}