// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Comic struct {
	ID          int32
	Titles      []string
	Author      pgtype.Text
	Description pgtype.Text
	Cover       pgtype.Text
	ComType     int32
	Status      int32
	PublishedIn []int32
	Genres      []int32
	CurrentChap int32
	ViewedChap  int32
	LastUpdate  int32
	Track       bool
	Deleted     bool
}
