// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package mysql

import (
	"database/sql"
	"time"
)

type Comic struct {
	ID          int32
	Author      sql.NullString
	Description sql.NullString
	Cover       sql.NullString
	ComType     int32
	Status      int32
	CurrentChap int32
	ViewedChap  int32
	LastUpdate  time.Time
	Track       bool
	Deleted     bool
}

type ComicGenre struct {
	ComicID int32
	Genre   int32
}

type ComicPublisher struct {
	ComicID   int32
	Publisher int32
}

type ComicTitle struct {
	ComicID int32
	Title   string
}
