// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlite

import (
	"database/sql"
)

type Comic struct {
	ID          int64
	Titles      string
	Author      sql.NullString
	Description sql.NullString
	Cover       sql.NullString
	ComType     int64
	Status      int64
	PublishedIn sql.NullString
	Genres      string
	CurrentChap int64
	ViewedChap  int64
	LastUpdate  int64
	Track       bool
	Deleted     bool
}
