global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  - rules.yml

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alert-manager:9093

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - prometheus:9090
  - job_name: comics
    static_configs:
      - targets:
        - localhost:8081
        - host.docker.internal:8083
