version: "3.8"
services:
  web:
    build:
      context: .
      # TODO: Change the path to clod
      dockerfile: Dockerfile
    ports:
      - 8080:8081
    # Important to bind/mount your codebase dir to /server dir for live reload
    volumes:
      - ./:/server