services:
  comics_server:
    container_name: comics_server
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - OTEL_EXPORTER_GRPC_ENDPOINT=host.docker.internal:4317
      - LOG_OUTPUT_FILE=.observability/log/docker_logs.log
      # 0.0.0.0 Needed to be available from host, outside the container
      - ADDRESS_HTTP=0.0.0.0:8083
      - ADDRESS_GRPC=0.0.0.0:8084
    ports:
      - 8083:8083
      - 8084:8084
    volumes:
      - ./.env:/app/.env:ro
      - ../src/db/comics.db:/src/db/comics.db:ro
      - ./.observability/log:/app/.observability/log
    restart: on-failure
    networks:
      - server_net

  mongodb:
    image : mongo
    container_name: mongodb
    ports:
    - 27017:27017
    healthcheck:
      test:
      - CMD
      - mongo
      - --eval
      - "db.adminCommand('ping')"
    restart: unless-stopped
    networks:
      - server_net

networks:
  server_net:
    driver: bridge