services:
  jaeger:
    image: jaegertracing/jaeger:latest
    container_name: jaeger
    environment:
      COLLECTOR_OTLP_ENABLED: true
      # COLLECTOR_ZIPKIN_HTTP_PORT: 9411
      # JAEGER_STORAGE_TYPE: memory
      # OTEL_TRACES_SAMPLER: always_off
    ports:
      - 5779:5779 # gRPC jaeger.api_v2.SamplingManager
      - 5778:5778 # HTTP /sampling

      - 4317:4317 # gRPC OTEL collector
      - 4318:4318 # HTTP OTEL collector /v1/traces
      # - 9411:9411 # HTTP ZipkinJSON /api/v2/spans /api/v1/spans
      # - 6831:6831/udp # Legacy Thrift compact
      # - 6832:6832/udp # Legacy Thrift binary
      # - 14250:14250 # gRPC Legacy Protobuf jaeger.api_v2.CollectorService
      # - 14268:14268 # HTTP Legacy Thrift /api/traces

      - 16685:16685 # gRPC OTLP-based Protobuf collector jaeger.api_v3.QueryService
      - 16686:16686 # HTTP OTLP-based /api/v3/* & /api/*
    volumes:
      # - ./jaeger-config.yaml:/etc/jaeger/jaeger-config.yaml
      - observer_vol:/var/jaeger
      - observer_vol:/tmp
    networks:
      - observability

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - 3100:3100
    command: -config.file=/mnt/config/loki-config.yaml
    volumes:
      - ./grafana/loki-config.yaml:/mnt/config/loki-config.yaml
    networks:
      - observability
  
  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    command: -config.file=/mnt/config/promtail-config.yml
    volumes:
      - ./grafana/promtail-config.yaml:/mnt/config/promtail-config.yml
      - ./log:/.observability/log
    links:
      - loki
    networks:
      - observability

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    environment:
      TARGETS: host.docker.internal:8082/metrics
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/rules.yml:/etc/prometheus/rules.yml
      - observer_vol:/prometheus
    networks:
      - observability
  
  alert-manager:
    container_name: alert-manager
    image: prom/alertmanager
    volumes:
      - ./prometheus/alertmanager.yml:/alertmanager/alertmanager.yml
      - observer_vol:/alertmanager
    ports:
      - 9093:9093
    networks:
      - observability

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=adm1n
      - GF_SECURITY_ADMIN_PASSWORD=adm1n
    volumes:
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - observer_vol:/var/lib/grafana
    networks:
      - observability

volumes:
  observer_vol:

networks:
  observability:
    driver: bridge